openapi: 3.0.0
info:
  description: This file contains the OpenAPI specifications for the Address APIs of **The Furniture Bros**.
  title: The Furniture Bros Address OpenAPI Specifications
  version: 1.0.0
servers:
  - url: https://thefurniturebros.com
    description: Production server
  - url: https://localhost:5000
    description: Local server
components:
  securitySchemes:
    APIKey:
      type: apiKey
      in: header
      name: "Authorization"
      description: |
        Provide your API key.
paths:
  /address/list:
    get:
      summary: Get Addresses
      description: |
        This endpoint allows you to get the list of addresses.
      tags:
        - Checkout
      security:
        - APIKey: []
      responses:
        "200":
          description: Successful response. Returns the user's address information.
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    description: Unique identifier for the user address record.
                  user:
                    type: object
                    description: Information about the user associated with the addresses.
                    properties:
                      _id:
                        type: string
                        description: Unique identifier for the user.
                      name:
                        type: string
                        description: Name of the user.
                  addresses:
                    type: array
                    description: List of addresses associated with the user.
                    items:
                      type: object
                      properties:
                        address:
                          type: string
                          description: The address of the location.
                        main:
                          type: boolean
                          description: Indicates if this address is the main address.
                        _id:
                          type: string
                          description: Unique identifier for the address.
                  __v:
                    type: integer
                    description: Version key for the address record.
                example:
                  _id: "6556dd7a50e4db57682be25c"
                  user:
                    _id: "6555a0f89feeac7dccd9b1dd"
                    name: "first account"
                  addresses:
                    - address: "383 Kent St, Sydney NSW 2000, Australia"
                      main: false
                      _id: "656bf54c99723847983a9714"
                    - address: "80 Collins St, Melbourne VIC 3000, Australia"
                      main: true
                      _id: "656d3c9b6f828da5305bad97"
                  __v: 53
        "400":
          description: See message description.
        "500":
          description: see message description.
  /address/api_key:
    get:
      summary: Get Google Places Key
      description: This endpoint allows you to get the API key for Google Places API. Learn more [here](https://developers.google.com/maps/documentation/places/web-service).
      tags:
        - Checkout
      security:
        - APIKey: []
      responses:
        "200":
          description: Successful response. The order has been created successfully.
          content:
            text/plain:
              schema:
                type: string
                description: The API key for Google Places.
                example: AIzaSyC6ASDCKAAS3G1E2EjRKlzk8TvHziasds"
        "400":
          description: See message description.
        "500":
          description: see message description.
  /address/add:
    post:
      summary: Add an Address
      description: This endpoint allows you to add an address for the user.
      tags:
        - Checkout
      security:
        - APIKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - address
              properties:
                address:
                  type: string
                  description: The address of the user to add. Newly added address will be selected as the main address.
            example:
              address: "383 Kent St, Sydney NSW 2000, Australia"
      responses:
        "200":
          description: Successful response. The order has been created successfully.
          content:
            text/plain:
              schema:
                type: string
                example: success
        "400":
          description: See message description.
        "500":
          description: see message description.
  /address/select:
    put:
      summary: Select Main Address
      description: This endpoint allows you to select the main address of the user.
      tags:
        - Checkout
      security:
        - APIKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - addressId
              properties:
                addressId:
                  type: string
                  description: |
                    The address ID of the user to be selected as the main address. 
                    Use the `GET get addresses` endpoint to look at the list of addresses, and it's ID.
              example:
                addressId: "656d3c9b6f828da5305bad97"
      responses:
        "200":
          description: Successful response. Returns the user's address information.
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    description: Unique identifier for the user address record.
                  user:
                    type: string
                    description: Unique identifier for the user.
                  addresses:
                    type: array
                    description: List of addresses associated with the user.
                    items:
                      type: object
                      properties:
                        address:
                          type: string
                          description: The address of the location.
                        main:
                          type: boolean
                          description: Indicates if this address is the main address.
                        _id:
                          type: string
                          description: Unique identifier for the address.
                  __v:
                    type: integer
                    description: Version key for the address record.
                example:
                  _id: "6556dd7a50e4db57682be25c"
                  user: "6555a0f89feeac7dccd9b1dd"
                  addresses:
                    - address: "383 Kent St, Sydney NSW 2000, Australia"
                      main: false
                      _id: "656bf54c99723847983a9714"
                    - address: "80 Collins St, Melbourne VIC 3000, Australia"
                      main: true
                      _id: "656d3c9b6f828da5305bad97"
                  __v: 53
        "400":
          description: See message description.
        "500":
          description: see message description.
  /address/delete:
    delete:
      summary: Delete an Address
      description: This endpoint allows you to delete an address.
      tags:
        - Checkout
      security:
        - APIKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - addressId
              properties:
                addressId:
                  type: string
                  description: |
                    The address ID of the user to be deleted. 
                    Use the `GET get addresses` endpoint to look at the list of addresses, and it's ID.
            example:
              addressId: "674b3347dc3d9360b4c32da3"
      responses:
        "200":
          description: Successful response. Returns the user's address information.
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    description: Unique identifier for the user address record.
                  user:
                    type: string
                    description: Unique identifier for the user.
                  addresses:
                    type: array
                    description: List of addresses associated with the user.
                    items:
                      type: object
                      properties:
                        address:
                          type: string
                          description: The address of the location.
                        main:
                          type: boolean
                          description: Indicates if this address is the main address.
                        _id:
                          type: string
                          description: Unique identifier for the address.
                  __v:
                    type: integer
                    description: Version key for the address record.
                example:
                  _id: "6556dd7a50e4db57682be25c"
                  user: "6555a0f89feeac7dccd9b1dd"
                  addresses:
                    - address: "383 Kent St, Sydney NSW 2000, Australia"
                      main: false
                      _id: "656bf54c99723847983a9714"
                    - address: "80 Collins St, Melbourne VIC 3000, Australia"
                      main: true
                      _id: "656d3c9b6f828da5305bad97"
                  __v: 53
        "400":
          description: See message description.
        "500":
          description: see message description.
